language: haskell
before_install:
  - git clone --quiet git://github.com/diagrams/diagrams-core.git diagrams/diagrams-core
  - cd diagrams
  - cabal install diagrams-core/
  - cd ..
notifications:
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams-lib\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
